version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.11.4

commands:
  tf-install:
    description: installs terraform binary
    parameters:
      version:
        type: string
        default: 0.11.11
      os:
        type: string
        default: linux
      arch:
        type: string
        default: amd64
    steps:
      - run:
          name: download terraform
          command: |
            curl -L -o /tmp/terraform.zip \
            https://releases.hashicorp.com/terraform/<< parameters.version >>/terraform_<< parameters.version >>_<< parameters.os >>_<< parameters.arch >>.zip
      - run: unzip -d /go/bin /tmp/terraform.zip

  acctest:
    description: "Run acceptance tests for cloud providers"
    parameters:
      provider:
        type: string
    steps:
      - checkout

      - run:
          name: install junit and setup test path
          command: |
            go get github.com/jstemmer/go-junit-report
            mkdir -p /tmp/test-results

      # spin up infrastructure
      - run:
          working_directory: ./test/tf/<< parameters.provider >>
          command: terraform init
      - run:
          working_directory: ./test/tf/<< parameters.provider >>
          command: terraform apply --auto-approve

      # run acceptance tests
      - run: go test -v ./provider/<< parameters.provider >> | go-junit-report > /tmp/test-results/unit-tests.xml

      # store test results for CircleCI
      - store_test_results:
          path: /tmp/test-results
      # teardown infrastructure
      - run:
          working_directory: ./test/tf/<< parameters.provider >>
          command: terraform destroy --force
          when: always
jobs:
  aws-provider:
    executor: go
    steps:
      - tf-install
      - acctest:
          provider: aws

workflows:
  version: 2
  acceptance:
    jobs:
      - aws-provider